<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Receipt {{ $invoice->number }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1c1e; padding: 48px; }
        .wordmark { font-size: 22px; font-weight: 700; letter-spacing: 2px; color: #124389; }
        .wordmark span { color: #6b53c4; }
        .tag { font-size: 9px; letter-spacing: 3px; color: #6b7280; text-transform: uppercase; margin-top: 2px; }
        .receipt-title { margin-top: 28px; font-size: 16px; font-weight: 700; color: #0f376f; }
        .receipt-no { font-size: 10px; color: #6b7280; margin-top: 2px; }
        .paid-chip { display: inline-block; margin-top: 10px; padding: 4px 14px; border: 2px solid #1d7a46; color: #1d7a46; font-weight: 700; font-size: 11px; letter-spacing: 2px; border-radius: 4px; }
        table.meta { width: 100%; margin-top: 26px; border-collapse: collapse; }
        table.meta td { padding: 7px 0; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
        table.meta td.label { width: 38%; color: #6b7280; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; }
        table.meta td.value { font-size: 12px; color: #1a1c1e; }
        .amount-row { margin-top: 26px; padding: 16px 18px; background: #eef4fb; border-radius: 6px; }
        .amount-label { font-size: 10px; text-transform: uppercase; letter-spacing: 2px; color: #0f376f; }
        .amount { font-size: 24px; font-weight: 700; color: #124389; margin-top: 4px; }
        .footer { margin-top: 40px; font-size: 9px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 12px; }
    </style>
</head>
<body>
    <div class="wordmark">MARK<span>DEV</span></div>
    <div class="tag">Payment receipt</div>

    <div class="receipt-title">{{ $invoice->title ?? 'Course fee' }}</div>
    <div class="receipt-no">Invoice {{ $invoice->number }}</div>
    <div class="paid-chip">PAID</div>

    @php($submission = $invoice->latestSubmission)
    <table class="meta">
        <tr>
            <td class="label">Received from</td>
            <td class="value">{{ $invoice->user?->name ?? 'Student' }}</td>
        </tr>
        @if ($invoice->feePlan?->course?->title)
            <tr>
                <td class="label">Course</td>
                <td class="value">{{ $invoice->feePlan->course->title }}</td>
            </tr>
        @endif
        <tr>
            <td class="label">Invoice type</td>
            <td class="value">{{ ucfirst(str_replace('_', ' ', $invoice->type ?? 'installment')) }}@if ($invoice->sequence_no) — installment #{{ $invoice->sequence_no }}@endif</td>
        </tr>
        <tr>
            <td class="label">Issued</td>
            <td class="value">{{ $invoice->issued_at?->format('F j, Y') ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Paid on</td>
            <td class="value">{{ $invoice->paid_at?->format('F j, Y') ?? '—' }}</td>
        </tr>
        @if ($submission)
            <tr>
                <td class="label">Payment method</td>
                <td class="value">{{ $submission->method_brand ?: \Illuminate\Support\Str::headline((string) $submission->method_type) }}</td>
            </tr>
            @if ($submission->reference_no)
                <tr>
                    <td class="label">Reference</td>
                    <td class="value">{{ $submission->reference_no }}</td>
                </tr>
            @endif
        @endif
        @if ($invoice->fine_amount > 0)
            <tr>
                <td class="label">Late-payment fine</td>
                <td class="value">{{ $invoice->currency }} {{ number_format((float) $invoice->fine_amount, 0) }} ({{ $invoice->fine_days }} days)</td>
            </tr>
        @endif
        @if ((float) $invoice->absence_fine_amount > 0)
            <tr>
                <td class="label">Absence fine</td>
                <td class="value">{{ $invoice->currency }} {{ number_format((float) $invoice->absence_fine_amount, 0) }}</td>
            </tr>
        @endif
        @if ((float) $invoice->absence_fine_credit > 0)
            <tr>
                <td class="label">Credit — corrected absence</td>
                <td class="value">− {{ $invoice->currency }} {{ number_format((float) $invoice->absence_fine_credit, 0) }}</td>
            </tr>
        @endif
    </table>

    <div class="amount-row">
        <div class="amount-label">Amount paid</div>
        <div class="amount">{{ $invoice->currency }} {{ number_format((float) $invoice->payable_total, 0) }}</div>
    </div>

    <div class="footer">
        Generated by the MarkDev student portal on {{ now()->format('F j, Y · H:i') }}. This receipt confirms payment recorded against invoice {{ $invoice->number }}.
    </div>
</body>
</html>
